### ISSUE TITLE
Is there a license for using this repository?

### ISSUE THREAD

**Issue by ForrestTrepte** [USDAForestService/ForestVegetationSimulator#5]
Hello. Is there a license that governs use of the [FVS software](https://www.fs.usda.gov/fvs/software/index.shtml) and this repository?

Many GitHub repositories use a [license file](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository) to designate their license. Without a license, it could be unclear who can use, change, or contribute to FVS.

**Comment by DavidLRfs** [comment]
Hello Forrest,

Anyone may download and use the FVS source code as it is public domain. Only FVS staff and a couple close cooperators may commit to the repository. Anyone is welcome to provide suggestions and code to the FVS staff and we will take it under consideration.

Attached is the license file included with our distributed FVS installation that can be obtained from our website (https://www.fs.usda.gov/fvs/).

Have a good day!
      Lance

From: Forrest Trepte ***@***.***>
Sent: Tuesday, September 6, 2022 3:31 PM
To: USDAForestService/ForestVegetationSimulator ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [USDAForestService/ForestVegetationSimulator] Is there a license for using this repository? (Issue #5)


Hello. Is there a license that governs use of the FVS software<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.fs.usda.gov%2Ffvs%2Fsoftware%2Findex.shtml&data=05%7C01%7C%7Cacca68d5d47a464356f808da904f1bc2%7Ced5b36e701ee4ebc867ee03cfa0d4697%7C0%7C0%7C637980966683118873%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=KV89mAA9xqRJY4Mpj33al03Ta%2Bl0abh2dKzMfoRvdyI%3D&reserved=0> and this repository?

Many GitHub repositories use a license file<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.github.com%2Fen%2Fcommunities%2Fsetting-up-your-project-for-healthy-contributions%2Fadding-a-license-to-a-repository&data=05%7C01%7C%7Cacca68d5d47a464356f808da904f1bc2%7Ced5b36e701ee4ebc867ee03cfa0d4697%7C0%7C0%7C637980966683118873%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=MERAJrjn4I8GgfSw3vI5CwUyGpzL242%2FlhTpiSK6h5M%3D&reserved=0> to designate their license. Without a license, it could be unclear who can use, change, or contribute to FVS.

-
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FUSDAForestService%2FForestVegetationSimulator%2Fissues%2F5&data=05%7C01%7C%7Cacca68d5d47a464356f808da904f1bc2%7Ced5b36e701ee4ebc867ee03cfa0d4697%7C0%7C0%7C637980966683118873%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=YF%2FxHhGyDDYfU68G6T3Eo3%2F70DmJQ2jQDTQuf9QJYxE%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAZVWHWYX6MSYBOVFUHXEZ43V46ZZVANCNFSM6AAAAAAQGGQC6I&data=05%7C01%7C%7Cacca68d5d47a464356f808da904f1bc2%7Ced5b36e701ee4ebc867ee03cfa0d4697%7C0%7C0%7C637980966683118873%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=YRtOh4obeicGCLVgf2j7is%2Fn64mYL8toirBSJFjPXb4%3D&reserved=0>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>




This electronic message contains information generated by the USDA solely for the intended recipients. Any unauthorized interception of this message or the use or disclosure of the information it contains may violate the law and subject the violator to civil or criminal penalties. If you believe you have received this message in error, please notify the sender and delete the email immediately.

May 20, 2022

Materials produced by employees of the United States Federal Government as part
of their official duties  are not entitled to domestic copyright protection
under United States law and are therefore in the U.S. public domain. The Forest
Vegetation Simulator is free and open-source software. It is released without
any conditions upon its use, and is available to everyone without restriction.

The software is provided "as is" without warranty of any kind, either expressed
or implied, including, but not limited to, the implied warranties of
merchantability and fitness for a particular purpose. In no event shall the
author be held liable for any damages arising from the use of this software.

The software package may include certain open source components that are subject
to open source licenses, in which case, the embedded open source software is
owned by a third party. The open source software is not subject to the terms and
conditions of this license. Instead, each item of open source software is
licensed under its applicable license terms. Nothing in this license limits your
rights under, nor grants you rights that supersede, the terms and conditions of
any applicable license terms for the open source software.

**Comment by ForrestTrepte** [comment]
Thanks, Lance!
